# H2内存数据库测试配置
spring:
  config:
    activate:
      on-profile: h2
      
  # H2内存数据源配置
  datasource:
    url: jdbc:h2:mem:manday_assess_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 5000
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  # H2控制台配置（可选，用于调试）
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # 禁用Flyway（使用JPA自动建表）
  flyway:
    enabled: false
    
  # 禁用Redis（测试环境不需要）
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
      timeout: 1000ms

# 日志配置
logging:
  level:
    gov.changsha.finance: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG