# 开发环境专用配置
# 支持灵活的端口配置和多实例启动

spring:
  config:
    activate:
      on-profile: dev
      
  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:5433/manday_assess_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      
  # JPA开发配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 服务器开发配置 - 支持环境变量端口配置
server:
  port: ${SERVER_PORT:${DEV_SERVER_PORT:8080}}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 日志开发配置
logging:
  level:
    gov.changsha.finance: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot.web.embedded.tomcat: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# 开发实例1配置 (默认端口)
spring:
  config:
    activate:
      on-profile: dev-instance-1

server:
  port: 8080

---
# 开发实例2配置
spring:
  config:
    activate:
      on-profile: dev-instance-2

server:
  port: 8081

---
# 开发实例3配置
spring:
  config:
    activate:
      on-profile: dev-instance-3

server:
  port: 8082

---
# 开发实例4配置
spring:
  config:
    activate:
      on-profile: dev-instance-4

server:
  port: 8083

---
# 开发实例5配置
spring:
  config:
    activate:
      on-profile: dev-instance-5

server:
  port: 8084